feat: first commit
apache/incubator-paimon-webui pull request #36
Opened 2023-09-07 03:33 UTC by labbomb

### Purpose

Please refer to the main `issue`  [#35](https://github.com/apache/incubator-paimon-webui/issues/35).

### Tests

### API and Format

### Documentation

2023-09-07 03:36 UTC, songjianet requested changes

2023-09-07 03:36 UTC, songjianet commented on paimon-web-ui-new/src/config/index.ts
> + */
delete this.

2023-09-07 03:36 UTC, songjianet commented on paimon-web-ui-new/src/config/index.ts
> +   */
delete this.

2023-09-07 03:36 UTC, songjianet commented on paimon-web-ui-new/src/main.ts
> +// 项目信息全局console
delete this.

2023-09-07 03:36 UTC, songjianet commented on paimon-web-ui-new/src/main.ts
> +// 家人们谁懂啊, \/\/\/ 天依蓝、镜音连、巡音粉、初音绿 /\/\/
delete this.

2023-09-07 03:36 UTC, songjianet commented on paimon-web-ui-new/vite.config.ts
> +        enabled: false, // 1、true时生成eslint配置文件，2、生成后改为false，避免重复消耗
use english

2023-09-07 03:53 UTC, songjianet approved these changes

2023-09-07 15:38 UTC, SteNicholas commented on paimon-web-ui-new/.eslintrc.cjs
> +/* eslint-env node */
Adds license for all cjs file.

2023-09-07 15:42 UTC, SteNicholas commented on paimon-web-ui-new/.eslintrc.cjs
> +/* eslint-env node */
Adds license for all cjs file. You could refer to [.eslintrc.cjs](https://github.com/apache/skywalking-booster-ui/blob/main/.eslintrc.cjs) of SkyWalking.

2023-09-07 15:43 UTC, SteNicholas commented on paimon-web-ui-new/.gitignore
> +# Logs
Could this .gitignore merge with the .gitignore in parent directory?

2023-09-07 15:43 UTC, SteNicholas commented on paimon-web-ui-new/.prettierrc.json
> +}
Add the new line at the end of this file.

2023-09-07 15:46 UTC, SteNicholas commented on paimon-web-ui-new/README.md
> +This template should help get you started developing with Vue 3 in Vite.
```suggestion
This UI starts from Vue 3 in Vite.
```

2023-09-07 15:47 UTC, SteNicholas commented on paimon-web-ui-new/README.md
> +## Recommended IDE Setup
```suggestion
## IDE Setup
```

2023-09-07 15:48 UTC, SteNicholas commented on paimon-web-ui-new/README.md
> +1. Disable the built-in TypeScript Extension
```suggestion
1. Disables the built-in TypeScript extension.
```

2023-09-07 15:48 UTC, SteNicholas commented on paimon-web-ui-new/README.md
> +    2) Find `TypeScript and JavaScript Language Features`, right click and select `Disable (Workspace)`
```suggestion
    2. Finds `TypeScript and JavaScript Language Features`, right click and select `Disable (Workspace)`.
```

2023-09-07 15:50 UTC, SteNicholas commented on paimon-web-ui-new/README.md
> +```
Add license detail like [README.md](https://github.com/apache/skywalking-booster-ui/blob/56a02293cfd3b62eb46d749895ff628f1830b116/README.md).

2023-09-07 15:54 UTC, SteNicholas commented on paimon-web-ui-new/src/main.ts
> +console.group('%cConsole', 'font-size:12px;color:#39C5BB;font-weight:300;');
Ditto.

2023-09-08 04:46 UTC, SteNicholas approved these changes
LGTM. @labbomb, thanks for updates.

2023-09-08 04:48 UTC, merged