feat: add playground
apache/incubator-paimon-webui pull request #42
Opened 2023-09-20 01:43 UTC by labbomb

### Purpose
New Playground module
<img width="1676" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/15062456/599d7087-beda-442e-a266-03317c9d0a2a">

### Tests

### API and Format

### Documentation

2023-09-20 01:52 UTC, songjianet requested changes

2023-09-20 01:52 UTC, songjianet commented on paimon-web-ui-new/src/components/monaco-editor/index.tsx
> +      // 监听值的变化
use english

2023-09-20 01:52 UTC, songjianet commented on paimon-web-ui-new/src/components/monaco-editor/index.tsx
> +      () => configStore.getCurrentTheme ,
Is there a space before the comma?

2023-09-20 01:52 UTC, songjianet commented on paimon-web-ui-new/src/views/playground/index.tsx
> +                <CataLog></CataLog>
<CataLog />

2023-09-20 01:52 UTC, songjianet commented on paimon-web-ui-new/src/views/playground/index.tsx
> +                  ></MonacoEditor>
<MonacoEditor />

2023-09-20 01:56 UTC, songjianet commented on paimon-web-ui-new/src/views/playground/index.tsx
> +                <CataLog></CataLog>
<CataLog />

2023-09-20 11:04 UTC, SteNicholas requested changes
@labbomb, thanks for the contribution. I have left some comments for this pull request. PTAL.

2023-09-20 11:04 UTC, SteNicholas commented on paimon-web-ui-new/src/locales/zh/modules/playground.ts
> +  select_catalog: '选择Catalog',
```suggestion
  select_catalog: '选择 Catalog',
```

2023-09-20 11:04 UTC, SteNicholas commented on paimon-web-ui-new/src/components/monaco-editor/type.ts
> +}
New line for the end of file.

2023-09-20 11:04 UTC, SteNicholas commented on paimon-web-ui-new/src/router/routes.ts
> +   * Login page
The indent of comment is incorrect.

2023-09-20 11:04 UTC, SteNicholas commented on paimon-web-ui-new/src/views/playground/index.tsx
> +      console.log('editor实例加载完成', editor)
```suggestion
      console.log('Loaded editor instance.', editor)
```

2023-09-21 09:40 UTC, SteNicholas approved these changes
LGTM. Thanks for @labbomb updates.

2023-09-21 09:41 UTC, merged