feat: perfect metadata model
apache/incubator-paimon-webui pull request #54
Opened 2023-10-16 02:59 UTC by hunter-cloud09

Perfect metadata model

re #51

2023-10-16 03:08 UTC, SteNicholas commented on paimon-web-api/pom.xml
> +            <artifactId>fastjson</artifactId>
Why use fastjson? IMO, fastjson has some security problem which is not recomeneded.

2023-10-16 07:43 UTC, hunter-cloud09 commented
@SteNicholas I have fixed them, PTAL.

2023-10-16 13:35 UTC, SteNicholas requested changes
@hunter-cloud09, thanks for updates. I left some comments for the updates. PTAL.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/constant/MetadataConstant.java
> +/** metadata constant. */
```suggestion
/** Metadata constant. */
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java
> +    @PostMapping("/querySchemaInfo")
```suggestion
    @PostMapping("/query/schema")
```
BTW, why use `PostMapping`? It's better to use `GetMapping` for query request.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java
> +    @PostMapping("/querySnapshotInfo")
Ditto.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java
> +    @PostMapping("/queryManifestInfo")
Ditto.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java
> +    @PostMapping("/queryDataFileInfo")
Ditto.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/QueryMetadataInfoDto.java
> +/** use for get table metadata. */
```suggestion
/** DTO of query metadata is used for getting table metadata. */
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/QueryMetadataInfoDto.java
> +public class QueryMetadataInfoDto {
```suggestion
public class QueryMetadataDTO {
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/MetadataFieldsModel.java
> +/** table metadata fields model. */
```suggestion
/** Model of metadata fields. */
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/DataFileInfoVo.java
> +    private final Long bucket;
```suggestion
    private final long bucket;
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/SnapshotInfoVo.java
> +/** metadata snapshot return value. */
Ditto.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/service/MetadataService.java
> +/** metadata service. */
```suggestion
/** Metadata service includes the service interfaces of metadata. */
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/service/MetadataService.java
> +    List<SchemaInfoVo> getSchemaInfo(QueryMetadataInfoDto dto);
Remove the `info` from all interfaces of `MetadataService`.

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/service/MetadataService.java
> +     * Retrieve a list of Metadata schema info.
```suggestion
     * Retrieves a list of Metadata schema.
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/MetadataServiceImpl.java
> +/** metadata service impl. */
```suggestion
/** The implementation of {@link MetadataService}. */
```

2023-10-16 13:35 UTC, SteNicholas commented on paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java
> +/** test for MetadataController. */
```suggestion
/** Tests for {@link MetadataController}. */
```

2023-10-17 01:54 UTC, hunter-cloud09 commented
@SteNicholas Fixed, PTAL.

2023-10-27 10:40 UTC, SteNicholas reviewed
@hunter-cloud09, there are some style that could be improved. PTAL.

2023-10-27 10:40 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/QueryMetadataDTO.java
> +    private String catalogName;
Adds the new line among fields.

2023-10-27 10:40 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/MetadataFieldsModel.java
> +    private int id;
Ditto.

2023-10-27 10:40 UTC, SteNicholas commented on paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/DataFileVO.java
> +    public static Builder builder() {
Could all VOs add the setter instead of builder?

2023-10-28 08:11 UTC, SteNicholas approved these changes
LGTM.

2023-10-28 08:31 UTC, SteNicholas approved these changes
LGTM.

2023-10-28 08:37 UTC, merged