[Feature] Enhance metadata table info module style
apache/incubator-paimon-webui pull request #74
Opened 2023-10-21 14:09 UTC by zhangmo8

### Purpose

Enhance metadata TableInfo module table and pagination

<img width="1020" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/43628500/2a316ca9-5533-418f-aa97-ecd7f71aa00b">

### Tests

### API and Format

### Documentation

2023-10-22 11:05 UTC, labbomb approved these changes
LGTM

2023-10-23 06:12 UTC, SteNicholas requested changes
@zhangmo8, thanks for contribution. I left a few comments for this pull request. PTAL.

2023-10-23 06:12 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +        title: 'Pk',
```suggestion
        title: 'Primary Key',
```

2023-10-23 06:12 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +        key: 'pk',
```suggestion
        key: 'primaryKey',
```

2023-10-23 06:12 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +          return <n-checkbox v-model:checked={rowData.pk} />
Ditto.

2023-10-23 06:12 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +        columnName: 'Desc',
```suggestion
        columnName: 'Description',
```

2023-10-23 06:23 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +        title: 'Operate',
```suggestion
        title: 'Operation',
```

2023-10-23 06:23 UTC, SteNicholas commented on paimon-web-ui-new/src/views/metadata/components/table/index.tsx
> +        key: 'actions',
```suggestion
        key: 'operation',
```

2023-10-23 06:30 UTC, SteNicholas approved these changes
LGTM. Thanks for @zhangmo8 updates.

2023-10-23 06:32 UTC, merged